name: Add to Project
on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
jobs:
  add-to-project:
    name: Add issue to project
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v2.0.0
        with:
          project-url: https://github.com/orgs/vala-lang/projects/4
          github-token: ${{ secrets.GH_ACTIONS_KEY }}