name: "PR Title Checker"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  check:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: Slashgear/action-check-pr-title@action-check-pr-title-v6.0.0
        with:
          regexp: '^(patch|feat|change|docs|change|test|chore)(\([a-zA-Z0-9 ._-]+\))?: .+$'